#!/usr/bin/env sh
# Step gitsign: generate .config/git/config.local, gitignored and included by
# .config/git/config. signingkey, gpgsign and gpg.ssh.program are MACHINE data:
# the brew prefix differs between Apple Silicon and Intel, and gpgsign without
# the key breaks every commit.

_gs_key="$HOME/.ssh/id_signing_sk.pub"
_gs_out="$DOTFILES_DIR/.config/git/config.local"
# Marker: tells a generated file from one the user wrote by hand.
_gs_mark="# generated by ./run install (step: gitsign) -- do not edit"
_gs_program=''
_gs_prefix=''

# --- an ssh-keygen able to handle sk-* keys (Apple's has no FIDO2) ---
# brew --prefix covers both /opt/homebrew (arm64) and /usr/local (intel).
if command -v brew >/dev/null 2>&1; then
  _gs_prefix=$(brew --prefix openssh 2>/dev/null || printf '')
fi
# An empty prefix would build "/bin/ssh-keygen", a path that exists on some
# systems and would be picked by mistake.
if [ -n "$_gs_prefix" ] && [ -x "$_gs_prefix/bin/ssh-keygen" ]; then
  _gs_program="$_gs_prefix/bin/ssh-keygen"
else
  # The hard-coded fallback is the ONLY route on Intel: prereqs.sh loads the
  # brew shellenv for Apple Silicon only, so `brew` may not be on PATH here.
  for _gs_cand in \
    /opt/homebrew/opt/openssh/bin/ssh-keygen \
    /usr/local/opt/openssh/bin/ssh-keygen; do
    if [ -x "$_gs_cand" ]; then
      _gs_program=$_gs_cand
      break
    fi
  done
fi
if [ -z "$_gs_program" ]; then
  # A preview must not warn about the machine it previews on: the full run
  # installs openssh through packages. Same rule as upgrade.sh.
  if [ "$DRY_RUN" = 1 ]; then
    log_info "[dry-run] no Homebrew openssh here -> the full run installs it"
  else
    log_warn "gitsign: no Homebrew openssh -> sk-* signing will fail (brew install openssh libfido2)"
  fi
fi

# --- build the wanted content ---
# Inside log.sh's private mktemp -d directory: a $$-derived name in a
# world-writable /tmp can be pre-created as a symlink, i.e. arbitrary write.
_gs_tmp="${_log_dir:?log.sh not sourced}/gitsign"
{
  printf '%s\n' "$_gs_mark"
  printf '%s\n' '# Machine-local git settings. Regenerate with: ./run install gitsign'
  printf '\n'
  printf '%s\n' '[gpg "ssh"]'
  printf '%s\n' '    # Machine data: git expands NO variable in pathname values (only ~),'
  printf '%s\n' '    # so the XDG-aware path is expanded here, at generation time.'
  printf '%s\n' "    allowedSignersFile = ${XDG_CONFIG_HOME:-$HOME/.config}/git/allowed_signers"
  if [ -n "$_gs_program" ]; then
    printf '%s\n' "    # Apple's ssh-keygen has no FIDO2 support: sk-* keys need this build."
    printf '%s\n' "    program = $_gs_program"
  fi
  printf '\n'
  if [ -r "$_gs_key" ]; then
    printf '%s\n' '[user]'
    printf '%s\n' "    signingkey = ~/${_gs_key#"$HOME"/}"
    printf '\n'
    printf '%s\n' '[commit]'
    printf '%s\n' '    # Enabled only because the signing key above exists on this machine.'
    printf '%s\n' '    gpgsign = true'
  else
    printf '%s\n' "# No ${_gs_key#"$HOME"/} here: signing left disabled on purpose."
    printf '%s\n' '# A missing key with gpgsign = true makes EVERY commit fail.'
  fi
} >"$_gs_tmp"

# --- write only when something actually changes ---
# No `rm` on the branches that leave $_gs_tmp behind: it lives inside $_log_dir,
# which log.sh removes by trap on EXIT, INT and TERM.
if [ -e "$_gs_out" ] && ! head -n 1 -- "$_gs_out" | grep -qF -- "$_gs_mark"; then
  # Hand-written file: never clobber settings the user put there.
  log_info "gitsign: config.local is hand-written -> left untouched"
elif [ -e "$_gs_out" ] && cmp -s -- "$_gs_tmp" "$_gs_out"; then
  log_ok "gitsign: config.local already up to date"
elif [ "$DRY_RUN" = 1 ]; then
  log_info "[dry-run] write ${_gs_out#"$DOTFILES_DIR"/}"
elif mv -- "$_gs_tmp" "$_gs_out"; then
  if [ -r "$_gs_key" ]; then
    log_ok "gitsign: config.local generated (signing enabled)"
  else
    log_ok "gitsign: config.local generated (signing disabled, no key here)"
  fi
else
  log_error "gitsign: cannot write ${_gs_out#"$DOTFILES_DIR"/}"
fi

# --- allowed_signers: one principal per identity, per signing key ---
# APPEND ONLY: an existing line is never rewritten, so a `valid-before` added
# by hand during a rotation survives every replay. And unlike config.local
# this file is TRACKED -- the one place `./run install` can dirty the repo,
# on purpose, only for a genuinely new key, and it says so.
_gs_signers="$DOTFILES_DIR/.config/git/allowed_signers"
_gs_added=0

# NAMED one by one, not a glob: `run` sets `set -f`, so a third forge file
# would be ignored in silence. Adding it here is the reminder that
# allowed_signers needs its principal too.
_gs_emails=$(
  for _gs_f in "$DOTFILES_DIR"/.config/git/config "$DOTFILES_DIR"/.config/git/config.gitlab; do
    [ -r "$_gs_f" ] && git config --file "$_gs_f" --get user.email 2>/dev/null
  done
)

# ONE signing key for both forges: a signature is not an access, so it needs
# no per-forge split the way the push keys do (.config/git/README.md).
_gs_blob=''
[ -r "$_gs_key" ] && _gs_blob=$(cut -d' ' -f2 -- "$_gs_key")
if [ -n "$_gs_blob" ]; then
  # OUT of the loop: per line, a run straddling midnight dated two principals
  # differently. Measured.
  _gs_day=$(date +%Y%m%d)
  for _gs_mail in $_gs_emails; do
    # Already there? The pair (principal, key) counts, not the line. awk
    # PRINTS its answer: an `exit` in the match block is overridden by END
    # (measured), and the CI's no-exit check cannot tell awk from shell.
    if [ -r "$_gs_signers" ] && [ "$(awk -v m="$_gs_mail" -v b="$_gs_blob" \
      '$1 == m { for (i = 2; i <= NF; i++) if ($i == b) f = 1 } END { print f + 0 }' \
      "$_gs_signers")" != 0 ]; then
      continue
    fi
    if [ "$DRY_RUN" = 1 ]; then
      log_info "[dry-run] allowed_signers += $_gs_mail (${_gs_key##*/})"
      continue
    fi
    # Without a final newline, appending glues this principal onto the last
    # line and `find-principals` skips the merged identity in silence -- it
    # returns the FIRST line whose key matches. Measured.
    [ -s "$_gs_signers" ] && [ -n "$(tail -c1 -- "$_gs_signers")" ] &&
      printf '\n' >>"$_gs_signers"
    # valid-after is TODAY: a commit older than it will not verify, and only
    # you know whether the key predates its registration. Hence the log line.
    if printf '%s namespaces="git",valid-after="%s" %s\n' \
      "$_gs_mail" "$_gs_day" "$(cat -- "$_gs_key")" >>"$_gs_signers"; then
      log_done "allowed_signers += $_gs_mail (${_gs_key##*/}, valid-after $_gs_day)"
      _gs_added=$((_gs_added + 1))
    else
      log_error "allowed_signers: cannot append to ${_gs_signers#"$DOTFILES_DIR"/}"
    fi
  done
fi
[ "$_gs_added" -gt 0 ] &&
  log_info "allowed_signers is TRACKED: commit the $_gs_added new line(s)"

unset _gs_key _gs_out _gs_mark _gs_program _gs_prefix _gs_cand _gs_tmp
unset _gs_signers _gs_added _gs_emails _gs_blob _gs_mail _gs_day
