#!/usr/bin/env sh
# Step gitsign: generate .config/git/config.local, gitignored and included by
# .config/git/config. signingkey, gpgsign and gpg.ssh.program are MACHINE data:
# a hard-coded /opt/homebrew path breaks every commit on Fedora, and gpgsign
# without the key breaks them just as well.

_gs_key="$HOME/.ssh/id_signing_sk.pub"
_gs_out="$DOTFILES_DIR/.config/git/config.local"
# Marker: tells a generated file from one the user wrote by hand.
_gs_mark="# generated by ./run install (step: gitsign) -- do not edit"
_gs_program=''
_gs_prefix=''

# --- an ssh-keygen able to handle sk-* keys (Apple's has no FIDO2) ----------
if is_macos; then
  # brew --prefix covers both /opt/homebrew (arm64) and /usr/local (intel).
  if command -v brew >/dev/null 2>&1; then
    _gs_prefix=$(brew --prefix openssh 2>/dev/null || printf '')
  fi
  # An empty prefix would build "/bin/ssh-keygen", a path that exists on some
  # systems and would be picked by mistake.
  if [ -n "$_gs_prefix" ] && [ -x "$_gs_prefix/bin/ssh-keygen" ]; then
    _gs_program="$_gs_prefix/bin/ssh-keygen"
  else
    for _gs_cand in \
      /opt/homebrew/opt/openssh/bin/ssh-keygen \
      /usr/local/opt/openssh/bin/ssh-keygen; do
      if [ -x "$_gs_cand" ]; then
        _gs_program=$_gs_cand
        break
      fi
    done
  fi
  if [ -z "$_gs_program" ]; then
    log_warn "gitsign: no Homebrew openssh -> sk-* signing will fail (brew install openssh libfido2)"
  fi
fi

# --- build the wanted content ----------------------------------------------
# Inside log.sh's private mktemp -d directory: a $$-derived name in a
# world-writable /tmp can be pre-created as a symlink, i.e. arbitrary write.
_gs_tmp="${_log_dir:?log.sh not sourced}/gitsign"
{
  printf '%s\n' "$_gs_mark"
  printf '%s\n' '# Machine-local git settings. Regenerate with: ./run install gitsign'
  printf '\n'
  printf '%s\n' '[gpg "ssh"]'
  printf '%s\n' '    # Machine data: git expands NO variable in pathname values (only ~),'
  printf '%s\n' '    # so the XDG-aware path is expanded here, at generation time.'
  printf '%s\n' "    allowedSignersFile = ${XDG_CONFIG_HOME:-$HOME/.config}/git/allowed_signers"
  if [ -n "$_gs_program" ]; then
    printf '%s\n' "    # Apple's ssh-keygen has no FIDO2 support: sk-* keys need this build."
    printf '%s\n' "    program = $_gs_program"
  fi
  printf '\n'
  if [ -r "$_gs_key" ]; then
    printf '%s\n' '[user]'
    printf '%s\n' "    signingkey = ~/${_gs_key#"$HOME"/}"
    printf '\n'
    printf '%s\n' '[commit]'
    printf '%s\n' '    # Enabled only because the signing key above exists on this machine.'
    printf '%s\n' '    gpgsign = true'
  else
    printf '%s\n' "# No ${_gs_key#"$HOME"/} here: signing left disabled on purpose."
    printf '%s\n' '# A missing key with gpgsign = true makes EVERY commit fail.'
  fi
} >"$_gs_tmp"

# --- write only when something actually changes -----------------------------
if [ -e "$_gs_out" ] && ! head -n 1 -- "$_gs_out" | grep -qF -- "$_gs_mark"; then
  # Hand-written file: never clobber settings the user put there.
  log_info "gitsign: config.local is hand-written -> left untouched"
  rm -f -- "$_gs_tmp"
elif [ -e "$_gs_out" ] && cmp -s -- "$_gs_tmp" "$_gs_out"; then
  log_ok "gitsign: config.local already up to date"
  rm -f -- "$_gs_tmp"
elif [ "$DRY_RUN" = 1 ]; then
  log_info "[dry-run] write ${_gs_out#"$DOTFILES_DIR"/}"
  rm -f -- "$_gs_tmp"
elif mv -- "$_gs_tmp" "$_gs_out"; then
  if [ -r "$_gs_key" ]; then
    log_ok "gitsign: config.local generated (signing enabled)"
  else
    log_ok "gitsign: config.local generated (signing disabled, no key here)"
  fi
else
  log_error "gitsign: cannot write ${_gs_out#"$DOTFILES_DIR"/}"
  rm -f -- "$_gs_tmp"
fi

unset _gs_key _gs_out _gs_mark _gs_program _gs_prefix _gs_cand _gs_tmp
