#!/usr/bin/env bash

# Common environment (XDG, EDITOR, PATH…) shared with zsh — POSIX file.
source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/env.sh"

# Non-interactive bash shells (scripts, `ssh host cmd`) load the MINIMAL
# env file, not this whole .bashrc: env + PATH available everywhere
# without leaking interactive behaviour into scripts.
export BASH_ENV="${XDG_CONFIG_HOME}/shell/env.sh"

# ===================== Beyond: interactive only =====================
case $- in *i*) ;; *) return ;; esac

# Fedora: system-wide settings for interactive non-login shells
# (/etc/profile.d/*.sh, vte.sh…). Harmless on macOS.
[[ -r /etc/bashrc ]] && source /etc/bashrc

# ------------------ History ------------------
export HISTFILE="${XDG_STATE_HOME}/bash/history"
mkdir -p "${HISTFILE%/*}"
HISTSIZE=100000
HISTFILESIZE=100000
HISTCONTROL=ignoreboth:erasedups
HISTTIMEFORMAT='%F %T '
shopt -s histappend
shopt -s cmdhist
shopt -s checkwinsize          # keep LINES/COLUMNS up to date on resize
# Share history across sessions (equiv. to SHARE_HISTORY in zsh). Idempotent.
case "${PROMPT_COMMAND:-}" in
  *"history -a"*) ;;
  *) PROMPT_COMMAND="history -a${PROMPT_COMMAND:+; $PROMPT_COMMAND}" ;;
esac

# ------------------ GPG ------------------
export GPG_TTY="$(tty)"

# ------------------ Completion ------------------
if [[ -r /opt/homebrew/etc/profile.d/bash_completion.sh ]]; then
  source /opt/homebrew/etc/profile.d/bash_completion.sh
elif [[ -r /usr/share/bash-completion/bash_completion ]]; then
  source /usr/share/bash-completion/bash_completion
fi
# mise: tools/environment per project + completion. The completion is
# generated by the `usage` CLI (installed via ~/.config/mise/config.toml);
# without the guard, every shell start would print an error.
if command -v mise >/dev/null 2>&1; then
  eval "$(mise activate bash --shims)"
  command -v usage >/dev/null 2>&1 && source <(mise completion bash)
fi

# ------------------ Aliases ------------------
[[ -r "${XDG_CONFIG_HOME}/shell/aliases.sh" ]] && source "${XDG_CONFIG_HOME}/shell/aliases.sh"

# ------------------ Tools init ------------------
# Guarded: a missing tool must never break the shell.
command -v zoxide   >/dev/null 2>&1 && eval "$(zoxide init bash)"
command -v fzf      >/dev/null 2>&1 && eval "$(fzf --bash)"
command -v starship >/dev/null 2>&1 && eval "$(starship init bash)"
