#!/usr/bin/env bash

# Common environment (XDG, EDITOR, PATH…) shared with zsh, POSIX file.
# Guarded like every other source: a partial install must not error on
# every bash start.
_env="${XDG_CONFIG_HOME:-$HOME/.config}/shell/env.sh"
[[ -r "$_env" ]] && source "$_env"
unset _env

# Non-interactive bash shells (scripts, `ssh host cmd`) load the MINIMAL
# env file, not this whole .bashrc: env + PATH available everywhere
# without leaking interactive behaviour into scripts.
# :- default everywhere below: if env.sh could not be sourced (partial
# install), an empty XDG_* silently turns "${XDG_STATE_HOME}/bash/history"
# into "/bash/history", an unwritable path, and no history at all.
export BASH_ENV="${XDG_CONFIG_HOME:-$HOME/.config}/shell/env.sh"

# ===================== Beyond: interactive only =====================
case $- in *i*) ;; *) return ;; esac

# Fedora: system-wide settings for interactive non-login shells
# (/etc/profile.d/*.sh, vte.sh…). Harmless on macOS.
[[ -r /etc/bashrc ]] && source /etc/bashrc

# ------------------ History ------------------
export HISTFILE="${XDG_STATE_HOME:-$HOME/.local/state}/bash/history"
mkdir -p -- "${HISTFILE%/*}"
HISTSIZE=100000
HISTFILESIZE=100000
HISTCONTROL=ignoreboth:erasedups
HISTTIMEFORMAT='%F %T '
shopt -s histappend
shopt -s cmdhist
shopt -s checkwinsize # keep LINES/COLUMNS up to date on resize
# Share history across sessions (equiv. to SHARE_HISTORY in zsh). Idempotent.
case "${PROMPT_COMMAND:-}" in
*"history -a"*) ;;
*) PROMPT_COMMAND="history -a${PROMPT_COMMAND:+; $PROMPT_COMMAND}" ;;
esac

# ------------------ Line editing ------------------
# Same reflexes as zsh (bindkey -v): vi mode in the fallback shell too.
set -o vi

# ------------------ GPG ------------------
# Only when stdin is a terminal: otherwise `tty` prints "not a tty" on
# stdout, which would poison GPG_TTY and break every pinentry.
if [ -t 0 ]; then
  GPG_TTY=$(tty)
  export GPG_TTY
fi

# ------------------ Completion ------------------
if [[ -r /opt/homebrew/etc/profile.d/bash_completion.sh ]]; then
  source /opt/homebrew/etc/profile.d/bash_completion.sh
elif [[ -r /usr/share/bash-completion/bash_completion ]]; then
  source /usr/share/bash-completion/bash_completion
fi
# mise: tools/environment per project + completion. The completion is
# generated by the `usage` CLI (installed via ~/.config/mise/config.toml);
# without the guard, every shell start would print an error.
if command -v mise >/dev/null 2>&1; then
  # --shims, not the hook: same resolution as BASH_ENV/scripts, and no
  # per-project [env] is used here.
  eval "$(mise activate bash --shims)"
  # Completion generated ONCE into the cache: regenerating it at every
  # startup costs a fork + generation for an identical result.
  # `./run upgrade` deletes the cache -> regenerated at the next shell.
  _mc="${XDG_CACHE_HOME:-$HOME/.cache}/bash/mise-completion.bash"
  if [[ ! -r "$_mc" ]] && command -v usage >/dev/null 2>&1; then
    mkdir -p -- "${_mc%/*}"
    mise completion bash >"$_mc" 2>/dev/null || rm -f -- "$_mc"
  fi
  [[ -r "$_mc" ]] && source "$_mc"
  unset _mc
fi

# ------------------ Aliases ------------------
_al="${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliases.sh"
# shellcheck source=/dev/null  # path known only at runtime; guarded by -r
[[ -r "$_al" ]] && source "$_al"
unset _al

# ------------------ Tools init ------------------
# Guarded: a missing tool must never break the shell.
command -v zoxide >/dev/null 2>&1 && eval "$(zoxide init bash)"
command -v fzf >/dev/null 2>&1 && eval "$(fzf --bash)"
command -v starship >/dev/null 2>&1 && eval "$(starship init bash)"

# ------------------ PATH re-assertion ------------------
# bash has no `typeset -U`: `mise activate --shims` above re-prepends a
# directory the parent shell already provided. Same final re-assertion
# zsh does in _zsh_build_path, expressed the bash way: first wins.
if command -v awk >/dev/null 2>&1; then
  PATH=$(printf '%s' "$PATH" | awk -v RS=: -v ORS=: '!s[$0]++')
  PATH=${PATH%:}
  export PATH
fi
