#!/usr/bin/env bash

# The environment shared with zsh. Guarded like every other source.
_env="${XDG_CONFIG_HOME:-$HOME/.config}/shell/env.sh"
# shellcheck source=/dev/null  # path known only at runtime; guarded by -r
[[ -r "$_env" ]] && source "$_env"
unset _env

# Non-interactive shells load the minimal env file, not this whole .bashrc:
# env and PATH everywhere, no interactive behaviour leaking into scripts.
# The :- defaults EVERYWHERE below: an empty XDG_STATE_HOME would turn the
# history path into "/bash/history", unwritable, and lose the history silently.
export BASH_ENV="${XDG_CONFIG_HOME:-$HOME/.config}/shell/env.sh"

# ===================== Beyond: interactive only =====================
case $- in *i*) ;; *) return ;; esac

# Fedora system-wide settings for interactive non-login shells. No-op on macOS.
[[ -r /etc/bashrc ]] && source /etc/bashrc

# ------------------ History ------------------
export HISTFILE="${XDG_STATE_HOME:-$HOME/.local/state}/bash/history"
[[ -d "${HISTFILE%/*}" ]] || mkdir -p -- "${HISTFILE%/*}"
HISTSIZE=100000
HISTFILESIZE=100000
HISTCONTROL=ignoreboth:erasedups
HISTTIMEFORMAT='%F %T '
shopt -s histappend
shopt -s cmdhist
shopt -s checkwinsize # keep LINES/COLUMNS up to date on resize
# Share history across sessions, zsh's SHARE_HISTORY. Idempotent.
case "${PROMPT_COMMAND:-}" in
  *"history -a"*) ;;
  *) PROMPT_COMMAND="history -a${PROMPT_COMMAND:+; $PROMPT_COMMAND}" ;;
esac

# ------------------ Line editing ------------------
# Same reflexes as zsh: vi mode in the fallback shell too.
set -o vi

# ------------------ GPG ------------------
# Only when stdin is a terminal: otherwise `tty` prints "not a tty" on STDOUT,
# which poisons GPG_TTY and breaks every pinentry.
if [ -t 0 ]; then
  GPG_TTY=$(tty)
  export GPG_TTY
fi

# ------------------ Completion ------------------
if [[ -r /opt/homebrew/etc/profile.d/bash_completion.sh ]]; then
  source /opt/homebrew/etc/profile.d/bash_completion.sh
elif [[ -r /usr/share/bash-completion/bash_completion ]]; then
  source /usr/share/bash-completion/bash_completion
fi
# The completion is generated by the `usage` CLI, itself installed by
# ~/.config/mise/config.toml; without the guard every start would error.
if command -v mise >/dev/null 2>&1; then
  # --shims, not the hook: same resolution as scripts get.
  eval "$(mise activate bash --shims)"
  # Generated once into the cache: regenerating at every startup costs a fork
  # for an identical result. `./run upgrade` invalidates it.
  _mc="${XDG_CACHE_HOME:-$HOME/.cache}/bash/mise-completion.bash"
  if [[ ! -r "$_mc" ]] && command -v usage >/dev/null 2>&1; then
    mkdir -p -- "${_mc%/*}"
    mise completion bash >"$_mc" 2>/dev/null || rm -f -- "$_mc"
  fi
  # shellcheck source=/dev/null  # generated file; guarded by -r
  [[ -r "$_mc" ]] && source "$_mc"
  unset _mc
fi

# ------------------ Aliases ------------------
_al="${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliases.sh"
# shellcheck source=/dev/null  # path known only at runtime; guarded by -r
[[ -r "$_al" ]] && source "$_al"
unset _al

# ------------------ Tools init ------------------
# Guarded: a missing tool must never break the shell.
command -v zoxide >/dev/null 2>&1 && eval "$(zoxide init bash)"
command -v fzf >/dev/null 2>&1 && eval "$(fzf --bash)"
command -v starship >/dev/null 2>&1 && eval "$(starship init bash)"

# ------------------ PATH re-assertion ------------------
# bash has no `typeset -U`, and `mise activate --shims` re-prepends a directory
# the parent shell already provided. Same re-assertion zsh does, first wins.
if command -v awk >/dev/null 2>&1; then
  PATH=$(printf '%s' "$PATH" | awk -v RS=: -v ORS=: '!s[$0]++')
  PATH=${PATH%:}
  export PATH
fi
